config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :materials
  resources :machines
  resources :teams
  devise_for :users
  root to: "entries#new"
  get 'pdf', to: "pages#pdf"
  resources :entries
end

app/models/material.rb
class Material < ApplicationRecord
  belongs_to :team

  monetize :current_rate_cents
  validates_presence_of :name
  validates_presence_of :unit
  validates_presence_of :tons_per_m3
  validates_presence_of :current_rate_cents
  validates_presence_of :currency
  validates :team_id, presence: true

end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_material, only: [:show, :edit, :update, :destroy]

  # GET /materials
  # GET /materials.json
  def index
    @materials = Material.all
  end

  # GET /materials/1
  # GET /materials/1.json
  def show
  end

  # GET /materials/new
  def new
    @material = Material.new
  end

  # GET /materials/1/edit
  def edit
  end

  # POST /materials
  # POST /materials.json
  def create
    @material = Material.new(material_params)

    respond_to do |format|
      if @material.save
        format.html { redirect_to @material, notice: 'Material was successfully created.' }
        format.json { render :show, status: :created, location: @material }
      else
        format.html { render :new }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /materials/1
  # PATCH/PUT /materials/1.json
  def update
    respond_to do |format|
      if @material.update(material_params)
        format.html { redirect_to @material, notice: 'Material was successfully updated.' }
        format.json { render :show, status: :ok, location: @material }
      else
        format.html { render :edit }
        format.json { render json: @material.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /materials/1
  # DELETE /materials/1.json
  def destroy
    @material.destroy
    respond_to do |format|
      format.html { redirect_to materials_url, notice: 'Material was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_material
      @material = Material.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def material_params
      params.require(:material).permit(:name, :unit, :team_id)
    end
end

app/views/materials/_form.html.erb
<%= form_with(model: material, local: true) do |form| %>
  <% if material.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(material.errors.count, "error") %> prohibited this material from being saved:</h2>

      <ul>
      <% material.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :team_id, value: current_user.team.id %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit %>
  </div>

  <div class="field">
    <%= form.label :rate, "Rate per unit" %>
    <%= form.text_field :current_rate %>
    <%= material.currency %>
  </div>

  <div class="field">
    <%= form.label :tons_per_m3, "Tons per m³" %>
    <%= form.text_field :tons_per_m3 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/materials/edit.html.erb
<h1>Editing Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Show', @material %> |
<%= link_to 'Back', materials_path %>

app/views/materials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Materials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @materials.each do |material| %>
      <tr>
        <td><%= material.name %></td>
        <td><%= material.unit %></td>
        <td><%= link_to 'Show', material %></td>
        <td><%= link_to 'Edit', edit_material_path(material) %></td>
        <td><%= link_to 'Destroy', material, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Material', new_material_path %>

app/views/materials/new.html.erb
<h1>New Material</h1>

<%= render 'form', material: @material %>

<%= link_to 'Back', materials_path %>

app/views/materials/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @material.name %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @material.unit %>
</p>
<%# humanized_money_with_symbol @product.price  %>
<%= link_to 'Edit', edit_material_path(@material) %> |
<%= link_to 'Back', materials_path %>