config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :materials
  resources :machines
  resources :teams
  devise_for :users
  root to: "entries#new"
  get 'pdf', to: "pages#pdf"
  resources :entries
end

app/models/machine.rb
class Machine < ApplicationRecord
  belongs_to :team

  validates :name, presence: true
end

app/controllers/machines_controller.rb
class MachinesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_machine, only: [:show, :edit, :update, :destroy]

  def index
    @machines = Machine.all
  end

  def show
  end

  def new
    @machine = Machine.new
  end

  def edit
  end

  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to @machine, notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: @machine }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_machine
      @machine = Machine.find(params[:id])
    end

    def machine_params
      params.require(:machine).permit(:name, :team_id, :last_hour_count)
    end
end

app/views/machines/_form.html.erb
<%= form_with(model: machine, local: true) do |form| %>
  <% if machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(machine.errors.count, "error") %> prohibited this machine from being saved:</h2>

      <ul>
      <% machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :team_id, value: current_user.team.id %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :last_hour_count, "Hours Count" %>
    <%= form.text_field :last_hour_count %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Machines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Hours Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @machines.each do |machine| %>
      <tr>
        <td><%= machine.name %></td>
        <td><%= machine.last_hour_count %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Machine', new_machine_path %>

app/views/machines/new.html.erb
<h1>New Machine</h1>

<%= render 'form', machine: @machine %>

<%= link_to 'Back', machines_path %>

app/views/machines/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @machine.name %>
</p>

<p>
  <strong>Hours Count:</strong>
  <%= @machine.last_hour_count %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>